# Write your MySQL query statement below
WITH AVG_EVENT AS (
    SELECT 
        EVENT_TYPE, 
        AVG(OCCURENCES) as AVG_OCCURENCES
    FROM
        EVENTS
    GROUP BY 1
),
TOTAL_EVENTS AS (
    SELECT
        BUSINESS_ID,
        EVENT_TYPE,
        SUM(OCCURENCES) AS SUM_OCCURENCES
    FROM
        EVENTS
    GROUP BY 1, 2
)
SELECT 
    BUSINESS_ID
FROM
    (
SELECT
    E.BUSINESS_ID,
    SUM(T.SUM_OCCURENCES > A.AVG_OCCURENCES) AS COMPARE
   
FROM
    EVENTS E
INNER JOIN
    AVG_EVENT A
ON
    E.EVENT_TYPE = A.EVENT_TYPE
INNER JOIN
    TOTAL_EVENTS T
ON
    T.BUSINESS_ID = E.BUSINESS_ID
AND 
