# Write your MySQL query statement below
SELECT 
    A.ID AS P1, B.ID AS P2, ABS(A.X_VALUE-B.X_VALUE)*ABS(A.Y_VALUE-B.Y_VALUE) AS AREA
FROM
    POINTS A
INNER JOIN 
    POINTS B
ON A.ID < B.ID
WHERE
    A.X_VALUE != B.X_VALUE
AND
    A.Y_VALUE != B.Y_VALUE
ORDER BY 3 DESC, 1,2
