# Write your MySQL query statement below
SELECT NAME  AS RESULTS FROM(
SELECT
    U.NAME, MR.USER_ID, COUNT(MR.rating)
    FROM
    MOVIE_RATING MR
    INNER JOIN
    USERS U
    ON MR.USER_ID = U.USER_ID
    GROUP BY 1,2
    ORDER BY 3 DESC, 1 ASC
    LIMIT 1) AS A
    
UNION
SELECT TITLE  AS RESULTS FROM(
    SELECT
    M.TITLE,MR.MOVIE_ID, AVG(MR.rating)
    FROM
    MOVIE_RATING MR
    INNER JOIN
    MOVIES M
    ON MR.MOVIE_ID = M.MOVIE_ID
    WHERE MONTH(CREATED_AT) = 2
    GROUP BY 1,2
    ORDER BY 3 DESC, 1 ASC
    LIMIT 1) AS B
    
​
