# Write your MySQL query statement below
SELECT QUERY_NAME, ROUND(AVG(RATING/POSITION),2) AS QUALITY,
    ROUND(SUM(CASE WHEN RATING < 3 THEN 1 ELSE 0 END)/COUNT(1) * 100, 2)AS poor_query_percentage
FROM QUERIES
GROUP BY 1
