# Write your MySQL query statement below
SELECT
    PERSON1,
    PERSON2,
    COUNT(*) AS CALL_COUNT,
    SUM(DURATION) AS TOTAL_DURATION
    FROM(
SELECT
    CASE WHEN FROM_ID < TO_ID THEN FROM_ID
    ELSE TO_ID END AS PERSON1,
    CASE WHEN TO_ID > FROM_ID THEN TO_ID
    ELSE FROM_ID END AS PERSON2,
    DURATION
FROM
    CALLS
    ) AS A
GROUP BY 1,2
