# Write your MySQL query statement below
WITH CTE AS(
SELECT A.NAME, COUNT(F.NAME) AS NUM_PLAYERS
FROM ACTIVITIES A
LEFT JOIN FRIENDS F
ON A.NAME = F.ACTIVITY
GROUP BY 1),
MAX_MIN AS(
SELECT
    MAX(NUM_PLAYERS) AS MAX_PLAYERS,
    MIN(NUM_PLAYERS) AS MIN_PLAYERS
FROM
    CTE)
​
SELECT
    NAME AS ACTIVITY
FROM
    CTE
WHERE
    NUM_PLAYERS < (SELECT MAX_PLAYERS FROM MAX_MIN)
AND
    NUM_PLAYERS > (SELECT MIN_PLAYERS FROM MAX_MIN)
​
# HAVING NUM_PLAYERS < MAX(NUM_PLAYERS)
# AND NUM_PLAYERS >  MIN(NUM_PLAYERS)
​
    
​
​
