# Write your MySQL query statement below
​
 SELECT A.NAME FROM(
SELECT
    E.NAME, COUNT(M.ID) AS COUNT_REPORTEES
FROM
    EMPLOYEE M
INNER JOIN
    EMPLOYEE E
ON
    E.ID = M. MANAGERID
GROUP BY 1
HAVING COUNT_REPORTEES >= 5
) AS A
​
