# Write your MySQL query statement below
​
SELECT NAME FROM(
SELECT
   C.NAME,CANDIDATEID, COUNT(1)
FROM
    VOTE   V
INNER JOIN
    CANDIDATE C
ON
    C.ID = V.CANDIDATEID
GROUP BY 1
ORDER BY 3 DESC
LIMIT 1) AS A
