# Write your MySQL query statement below
SELECT A.BOOK_ID, A.NAME FROM(
SELECT
    B.BOOK_ID, B.NAME, SUM(IFNULL(O.QUANTITY,0)) AS TOTAL_BOOKS
FROM
    BOOKS B
LEFT JOIN
    ORDERS O
ON
    O.BOOK_ID = B.BOOK_ID
AND
    O.dispatch_date > DATE_SUB('2019-06-23', INTERVAL 1 YEAR)
WHERE
    B.AVAILABLE_FROM < DATE_SUB('2019-06-23', INTERVAL 1 MONTH)
GROUP BY 1
HAVING TOTAL_BOOKS < 10) AS A
