# Write your MySQL query statement below
SELECT ACTOR_ID, DIRECTOR_ID FROM (
SELECT
    ACTOR_ID, DIRECTOR_ID, COUNT(1) as COOPERATION
FROM
    ACTORDIRECTOR
GROUP BY 1, 2
HAVING COOPERATION >= 3) AS A
