# Write your MySQL query statement below
WITH AGG_UNIT AS (SELECT
    PRODUCT_ID, SUM(UNIT) AS UNIT
FROM
    ORDERS
WHERE MONTH(ORDER_DATE) = 2
GROUP BY 1
HAVING UNIT >= 100)
SELECT
    PRODUCT_NAME, AGG_UNIT.UNIT
FROM
    PRODUCTS
INNER JOIN
    AGG_UNIT
ON
    PRODUCTS.PRODUCT_ID = AGG_UNIT.PRODUCT_ID
    
    
