# Write your MySQL query statement below
SELECT
    PROJECT.PROJECT_ID, ROUND(AVG(EMPLOYEE.EXPERIENCE_YEARS),2) as average_years 
FROM
    Employee
INNER JOIN
    PROJECT
ON
    EMPLOYEE.EMPLOYEE_ID = PROJECT.EMPLOYEE_ID
GROUP BY 1
