# Write your MySQL query statement below
SELECT
    A.NAME,
    SUM(AMOUNT) AS BALANCE
FROM
    USERS A
INNER JOIN
    TRANSACTIONS T
ON
    A.ACCOUNT = T.ACCOUNT
GROUP BY 1
HAVING SUM(AMOUNT)> 10000
