# Write your MySQL query statement below
SELECT 
    C.CUSTOMER_ID,
    C.NAME
FROM
    CUSTOMERS C
INNER JOIN  
(SELECT
    C.CUSTOMER_ID, SUM(CASE WHEN MONTH(O.ORDER_DATE) = 6 THEN (O.QUANTITY* P.PRICE) ELSE 0 END) AS JUNE_PURCHASE,SUM(CASE WHEN MONTH(O.ORDER_DATE) = 7 THEN (O.QUANTITY* P.PRICE) ELSE 0 END) AS JULY_PURCHASE
FROM
    CUSTOMERS C
INNER JOIN
    ORDERS O
ON 
    C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN
    PRODUCT P
ON
    P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    MONTH(O.ORDER_DATE) in (6,7)
AND
    YEAR(O.ORDER_DATE) = 2020
GROUP BY 1
HAVING JUNE_PURCHASE >= 100 AND JULY_PURCHASE >= 100) AS A
ON 
    C.CUSTOMER_ID = A.CUSTOMER_ID
​
