# Write your MySQL query statement below
WITH PC AS(SELECT
    P.ID, C.NAME
FROM
    PERSON  P
INNER JOIN
    COUNTRY C
ON
    C.COUNTRY_CODE = SUBSTRING(PHONE_NUMBER, 1, 3)),
DURATION AS(
SELECT CALLER_ID AS ID, DURATION FROM CALLS
UNION ALL
SELECT CALLEE_ID AS ID, DURATION FROM CALLS
),
AVG_DURATION AS(
SELECT
    NAME AS COUNTRY, AVG(DURATION) AS AVG_DUR
FROM
    PC P
INNER JOIN
    DURATION D
ON
    P.ID = D.ID
GROUP BY 1)
SELECT COUNTRY FROM AVG_DURATION WHERE AVG_DUR > (
    SELECT (2*SUM(DURATION))/(2*COUNT(1)) AS GLOBAL_DURATION
    FROM CALLS
 )
