# Write your MySQL query statement below
SELECT 
    SUM(COALESCE(B.APPLE_COUNT,0)+COALESCE(C.APPLE_COUNT,0)) AS APPLE_COUNT, SUM(COALESCE(B.ORANGE_COUNT,0) + COALESCE(C.ORANGE_COUNT,0)) AS ORANGE_COUNT
FROM
    BOXES B
LEFT JOIN
    CHESTS C
ON
    B.CHEST_ID = C.CHEST_ID
